In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
data = pd.read_csv(r"C:\Users\symbi\Downloads\House_Pricing.csv")

data.head()

,ID,Date House was Sold,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Waterfront View,No of Times Visited,...,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Renovated Year,Zipcode,Latitude,Longitude,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft)
0,7129300520,14 October 2017,221900.0,3,1.00,1180.0,5650.0,1.0,No,NaN,...,7,1180.0,0,63,0,98178.0,47.5112,-122.257,1340.0,5650
1,6414100192,14 December 2017,538000.0,3,2.25,2570.0,7242.0,2.0,No,NaN,...,7,2170.0,400,67,1991,98125.0,47.7210,-122.319,1690.0,7639
2,5631500400,15 February 2016,180000.0,2,1.00,770.0,10000.0,1.0,No,NaN,...,6,770.0,0,85,0,98028.0,47.7379,-122.233,2720.0,8062
3,2487200875,14 December 2017,604000.0,4,3.00,1960.0,5000.0,1.0,No,NaN,...,7,1050.0,910,53,0,98136.0,47.5208,-122.393,1360.0,5000
4,1954400510,15 February 2016,510000.0,3,2.00,1680.0,8080.0,1.0,No,NaN,...,8,1680.0,0,31,0,98074.0,47.6168,-122.045,1800.0,7503

## Dataset Overview

In [3]:
data.shape

(21613, 21)

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   ID                                         21613 non-null  int64
 1   Date House was Sold                        21613 non-null  object
 2   Sale Price                                 21609 non-null  float64
 3   No of Bedrooms                             21613 non-null  int64
 4   No of Bathrooms                            21609 non-null  float64
 5   Flat Area (in Sqft)                        21604 non-null  float64
 6   Lot Area (in Sqft)                         21604 non-null  float64
 7   No of Floors                               21613 non-null  float64
 8   Waterfront View                            21613 non-null  object
 9   No of Times Visited                        2124 non-null   object
 10  Condition of the House                     21613 non-null  object
 11  Overall Grade                              21613 non-null  int64
 12  Area of the House from Basement (in Sqft)  21610 non-null  float64
 13  Basement Area (in Sqft)                    21613 non-null  int64
 14  Age of House (in Years)                    21613 non-null  int64
 15  Renovated Year                             21613 non-null  int64
 16  Zipcode                                    21612 non-null  float64
 17  Latitude                                   21612 non-null  float64
 18  Longitude                                  21612 non-null  float64
 19  Living Area after Renovation (in Sqft)     21612 non-null  float64
 20  Lot Area after Renovation (in Sqft)        21613 non-null  int64
dtypes: float64(10), int64(7), object(4)
memory usage: 3.5+ MB

In [5]:
data.describe()

,ID,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Renovated Year,Zipcode,Latitude,Longitude,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft)
count,2.161300e+04,2.160900e+04,21613.000000,21609.000000,21604.000000,2.160400e+04,21613.000000,21613.000000,21610.000000,21613.000000,21613.000000,21613.000000,21612.000000,21612.000000,21612.000000,21612.000000,21613.000000
mean,4.580302e+09,5.401984e+05,3.370842,2.114732,2079.931772,1.510776e+04,1.494309,7.623467,1788.344193,291.509045,46.994864,84.402258,98077.937766,47.560048,-122.213892,1986.538914,12768.455652
std,2.876566e+09,3.673890e+05,0.930062,0.770138,918.487597,4.142827e+04,0.539989,1.105439,827.982604,442.575043,29.373411,401.679240,53.505425,0.138565,0.140830,685.404255,27304.179631
min,1.000102e+06,7.500000e+04,0.000000,0.000000,290.000000,5.200000e+02,1.000000,1.000000,290.000000,0.000000,3.000000,0.000000,98001.000000,47.155900,-122.519000,399.000000,651.000000
25%,2.123049e+09,3.219500e+05,3.000000,1.750000,1429.250000,5.040000e+03,1.000000,7.000000,1190.000000,0.000000,21.000000,0.000000,98033.000000,47.470975,-122.328000,1490.000000,5100.000000
50%,3.904930e+09,4.500000e+05,3.000000,2.250000,1910.000000,7.617500e+03,1.500000,7.000000,1560.000000,0.000000,43.000000,0.000000,98065.000000,47.571800,-122.230000,1840.000000,7620.000000
75%,7.308900e+09,6.450000e+05,4.000000,2.500000,2550.000000,1.068825e+04,2.000000,8.000000,2210.000000,560.000000,67.000000,0.000000,98118.000000,47.678000,-122.125000,2360.000000,10083.000000
max,9.900000e+09,7.700000e+06,33.000000,8.000000,13540.000000,1.651359e+06,3.500000,10.000000,9410.000000,4820.000000,118.000000,2015.000000,98199.000000,47.777600,-121.315000,6210.000000,871200.000000

In [6]:
data.columns

Index(['ID', 'Date House was Sold', 'Sale Price', 'No of Bedrooms',
       'No of Bathrooms', 'Flat Area (in Sqft)', 'Lot Area (in Sqft)',
       'No of Floors', 'Waterfront View', 'No of Times Visited',
       'Condition of the House', 'Overall Grade',
       'Area of the House from Basement (in Sqft)', 'Basement Area (in Sqft)',
       'Age of House (in Years)', 'Renovated Year', 'Zipcode', 'Latitude',
       'Longitude', 'Living Area after Renovation (in Sqft)',
       'Lot Area after Renovation (in Sqft)'],
      dtype='object')

## Duplicate Removal

In [7]:
data.duplicated().sum()

np.int64(0)

In [8]:
duplicate_columns = []

for i in range(len(data.columns)):
    for j in range(i):

        if data.iloc[:, i].equals(data.iloc[:, j]):
            duplicate_columns.append(data.columns[i])

print("Duplicate columns:", duplicate_columns)

Duplicate columns: []

## Handling Missing Values

In [9]:
data.isnull().sum()

ID                                               0
Date House was Sold                              0
Sale Price                                       4
No of Bedrooms                                   0
No of Bathrooms                                  4
Flat Area (in Sqft)                              9
Lot Area (in Sqft)                               9
No of Floors                                     0
Waterfront View                                  0
No of Times Visited                          19489
Condition of the House                           0
Overall Grade                                    0
Area of the House from Basement (in Sqft)        3
Basement Area (in Sqft)                          0
Age of House (in Years)                          0
Renovated Year                                   0
Zipcode                                          1
Latitude                                         1
Longitude                                        1
Living Area after Renovation (in Sqft)           1
Lot Area after Renovation (in Sqft)              0
dtype: int64

In [10]:
data['No of Times Visited'].value_counts(dropna=False)

No of Times Visited
NaN       19489
Twice       963
Thrice      510
Once        332
Four        319
Name: count, dtype: int64

In [11]:
data['No of Times Visited'] = data['No of Times Visited'].fillna('None')

In [12]:
data['No of Times Visited'].value_counts(dropna=False)

No of Times Visited
None      19489
Twice       963
Thrice      510
Once        332
Four        319
Name: count, dtype: int64

In [14]:
numerical_columns = data.select_dtypes(
    include=np.number
).columns

numerical_columns

Index(['ID', 'Sale Price', 'No of Bedrooms', 'No of Bathrooms',
       'Flat Area (in Sqft)', 'Lot Area (in Sqft)', 'No of Floors',
       'Overall Grade', 'Area of the House from Basement (in Sqft)',
       'Basement Area (in Sqft)', 'Age of House (in Years)', 'Renovated Year',
       'Zipcode', 'Latitude', 'Longitude',
       'Living Area after Renovation (in Sqft)',
       'Lot Area after Renovation (in Sqft)'],
      dtype='object')

In [15]:
for col in numerical_columns:

    if col != 'Sale Price':

        if data[col].isnull().sum() > 0:

            data[col] = data[col].fillna(
                data[col].median()
            )

In [16]:
categorical_columns = data.select_dtypes(
    include='object'
).columns

categorical_columns

Index(['Date House was Sold', 'Waterfront View', 'No of Times Visited',
       'Condition of the House'],
      dtype='object')

In [17]:
for col in categorical_columns:

    if data[col].isnull().sum() > 0:

        data[col] = data[col].fillna(
            data[col].mode()[0]
        )

In [19]:
data.dropna(subset=['Sale Price'], inplace=True)

In [20]:
data['Sale Price'].isnull().sum()

np.int64(0)

In [21]:
data.isnull().sum().sum()

np.int64(0)

## Data-Type Handling

In [22]:
data['Date House was Sold'] = pd.to_datetime(
    data['Date House was Sold']
)

In [23]:
data['Date House was Sold'].dtype

dtype('<M8[ns]')

In [24]:
data['Sale Year'] = data['Date House was Sold'].dt.year
data['Sale Month'] = data['Date House was Sold'].dt.month

In [25]:
data.drop(
    columns=['Date House was Sold'],
    inplace=True
)

## Encoding Categorical Variables

In [26]:
data.select_dtypes(include='object').columns

Index(['Waterfront View', 'No of Times Visited', 'Condition of the House'], dtype='object')

In [27]:
data['Waterfront View'].value_counts()

Waterfront View
No     21446
Yes      163
Name: count, dtype: int64

In [28]:
data['Waterfront View'] = data['Waterfront View'].map({
    'No': 0,
    'Yes': 1
})

In [29]:
visit_mapping = {
    'None': 0,
    'Once': 1,
    'Twice': 2,
    'Thrice': 3,
    'Four': 4
}

data['No of Times Visited'] = data[
    'No of Times Visited'
].map(visit_mapping)

In [30]:
data['Condition of the House'].value_counts()

Condition of the House
Fair         14028
Good          5678
Excellent     1701
Okay           172
Bad             30
Name: count, dtype: int64

In [31]:
condition_mapping = {
    'Bad': 1,
    'Okay': 2,
    'Fair': 3,
    'Good': 4,
    'Excellent': 5
}

data['Condition of the House'] = data[
    'Condition of the House'
].map(condition_mapping)

In [32]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 21609 entries, 0 to 21612
Data columns (total 22 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   ID                                         21609 non-null  int64
 1   Sale Price                                 21609 non-null  float64
 2   No of Bedrooms                             21609 non-null  int64
 3   No of Bathrooms                            21609 non-null  float64
 4   Flat Area (in Sqft)                        21609 non-null  float64
 5   Lot Area (in Sqft)                         21609 non-null  float64
 6   No of Floors                               21609 non-null  float64
 7   Waterfront View                            21609 non-null  int64
 8   No of Times Visited                        21609 non-null  int64
 9   Condition of the House                     21609 non-null  int64
 10  Overall Grade                              21609 non-null  int64
 11  Area of the House from Basement (in Sqft)  21609 non-null  float64
 12  Basement Area (in Sqft)                    21609 non-null  int64
 13  Age of House (in Years)                    21609 non-null  int64
 14  Renovated Year                             21609 non-null  int64
 15  Zipcode                                    21609 non-null  float64
 16  Latitude                                   21609 non-null  float64
 17  Longitude                                  21609 non-null  float64
 18  Living Area after Renovation (in Sqft)     21609 non-null  float64
 19  Lot Area after Renovation (in Sqft)        21609 non-null  int64
 20  Sale Year                                  21609 non-null  int32
 21  Sale Month                                 21609 non-null  int32
dtypes: float64(10), int32(2), int64(10)
memory usage: 3.6 MB

In [33]:
data.select_dtypes(include='object').columns

Index([], dtype='object')

In [34]:
data.isnull().sum().sum()

np.int64(0)

## Outlier Removal

In [35]:
outlier_columns = [
    'No of Bedrooms',
    'No of Bathrooms',
    'Flat Area (in Sqft)',
    'Lot Area (in Sqft)',
    'Area of the House from Basement (in Sqft)',
    'Basement Area (in Sqft)',
    'Living Area after Renovation (in Sqft)',
    'Lot Area after Renovation (in Sqft)'
]

In [36]:
for col in outlier_columns:

    Q1 = data[col].quantile(0.25)
    Q3 = data[col].quantile(0.75)

    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = data[
        (data[col] < lower_bound) |
        (data[col] > upper_bound)
    ]

    print(
        col,
        "| Lower:", round(lower_bound, 2),
        "| Upper:", round(upper_bound, 2),
        "| Outliers:", len(outliers)
    )

No of Bedrooms | Lower: 1.5 | Upper: 5.5 | Outliers: 545
No of Bathrooms | Lower: 0.62 | Upper: 3.62 | Outliers: 571
Flat Area (in Sqft) | Lower: -250.0 | Upper: 4230.0 | Outliers: 572
Lot Area (in Sqft) | Lower: -3430.5 | Upper: 19157.5 | Outliers: 2423
Area of the House from Basement (in Sqft) | Lower: -340.0 | Upper: 3740.0 | Outliers: 610
Basement Area (in Sqft) | Lower: -840.0 | Upper: 1400.0 | Outliers: 496
Living Area after Renovation (in Sqft) | Lower: 185.0 | Upper: 3665.0 | Outliers: 544
Lot Area after Renovation (in Sqft) | Lower: -2376.0 | Upper: 17560.0 | Outliers: 2193

In [37]:
for col in outlier_columns:

    Q1 = data[col].quantile(0.25)
    Q3 = data[col].quantile(0.75)

    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = data[
        (data[col] < lower_bound) |
        (data[col] > upper_bound)
    ]

    print("\n", col)
    print("Minimum:", data[col].min())
    print("Maximum:", data[col].max())
    print("Outlier Minimum:", outliers[col].min())
    print("Outlier Maximum:", outliers[col].max())

 No of Bedrooms
Minimum: 0
Maximum: 33
Outlier Minimum: 0
Outlier Maximum: 33

 No of Bathrooms
Minimum: 0.0
Maximum: 8.0
Outlier Minimum: 0.0
Outlier Maximum: 8.0

 Flat Area (in Sqft)
Minimum: 290.0
Maximum: 13540.0
Outlier Minimum: 4240.0
Outlier Maximum: 13540.0

 Lot Area (in Sqft)
Minimum: 520.0
Maximum: 1651359.0
Outlier Minimum: 19163.0
Outlier Maximum: 1651359.0

 Area of the House from Basement (in Sqft)
Minimum: 290.0
Maximum: 9410.0
Outlier Minimum: 3745.0
Outlier Maximum: 9410.0

 Basement Area (in Sqft)
Minimum: 0
Maximum: 4820
Outlier Minimum: 1410
Outlier Maximum: 4820

 Living Area after Renovation (in Sqft)
Minimum: 399.0
Maximum: 6210.0
Outlier Minimum: 3670.0
Outlier Maximum: 6210.0

 Lot Area after Renovation (in Sqft)
Minimum: 651
Maximum: 871200
Outlier Minimum: 17584
Outlier Maximum: 871200

In [38]:
data.sort_values(
    by='No of Bedrooms',
    ascending=False
)[
    [
        'No of Bedrooms',
        'No of Bathrooms',
        'Flat Area (in Sqft)',
        'Lot Area (in Sqft)',
        'Sale Price'
    ]
].head(20)

,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),Sale Price
15870,33,1.75,1620.0,6000.0,640000.0
8757,11,3.00,3000.0,4960.0,520000.0
19254,10,3.00,2920.0,3745.0,660000.0
13314,10,5.25,4590.0,10920.0,1150000.0
15161,10,2.00,3610.0,11914.0,650000.0
16844,9,4.00,4620.0,5508.0,1400000.0
18443,9,3.00,2820.0,4480.0,934000.0
4235,9,3.00,3680.0,4400.0,700000.0
4096,9,4.50,3830.0,6988.0,599999.0
6079,9,4.50,3650.0,5000.0,1280000.0
8546,9,7.50,4050.0,6504.0,450000.0
18477,8,4.00,7710.0,11750.0,3300000.0
9077,8,2.50,2280.0,3000.0,700000.0
4035,8,6.00,4340.0,9415.0,2150000.0
17235,8,3.50,4440.0,6480.0,1970000.0
15670,8,2.75,2530.0,4800.0,680000.0
6174,8,2.75,2790.0,6695.0,340000.0
12885,8,3.75,3460.0,4600.0,808000.0
19302,8,3.00,3840.0,15990.0,575000.0
4067,8,3.00,2850.0,12714.0,373000.0

In [39]:
data.sort_values(
    by='No of Bathrooms',
    ascending=False
)[
    [
        'No of Bedrooms',
        'No of Bathrooms',
        'Flat Area (in Sqft)',
        'Sale Price'
    ]
].head(20)

       No of Bedrooms  No of Bathrooms  Flat Area (in Sqft)  Sale Price
7252                6             8.00              12050.0   7700000.0
12777               7             8.00              13540.0   2280000.0
9254                6             7.75               9890.0   6890000.0
8546                9             7.50               4050.0    450000.0
4024                7             6.75               7480.0    800000.0
8092                5             6.75               9640.0   4670000.0
21506               5             6.50               7270.0   2240000.0
20578               6             6.50               6260.0   1180000.0
14556               5             6.25               8670.0   2890000.0
18302               5             6.25               8020.0   3300000.0
1315                6             6.00               7390.0   5300000.0
4035                8             6.00               4340.0   2150000.0
21050               5             6.00               7120.0    900000.0
21344               5             6.00               6880.0   1490000.0
12370               5             6.00               7440.0   4210000.0
19148               5             6.00               5490.0   3640000.0
4411                5             5.75               9200.0   5570000.0
16773               5             5.75               7730.0   1920000.0
15751               7             5.75               3700.0    540000.0
6501                4             5.75               7220.0   1940000.0

##### Outliers were identified using the IQR method. However, extreme observations in area-related features were retained because they may represent legitimate large or luxury properties. Only clearly unrealistic or anomalous observations were considered for removal.

In [40]:
data['No of Bedrooms'].value_counts().sort_index()

No of Bedrooms
0       13
1      199
2     2759
3     9823
4     6881
5     1601
6      271
7       38
8       13
9        6
10       3
11       1
33       1
Name: count, dtype: int64

In [41]:
data = data[data['No of Bedrooms'] != 33]

In [42]:
data.shape

(21608, 22)

In [43]:
columns_to_validate = [
    'No of Bedrooms',
    'No of Bathrooms',
    'Flat Area (in Sqft)',
    'Lot Area (in Sqft)',
    'Area of the House from Basement (in Sqft)',
    'Basement Area (in Sqft)',
    'Living Area after Renovation (in Sqft)',
    'Lot Area after Renovation (in Sqft)'
]

for col in columns_to_validate:
    print(col, "Negative values:", (data[col] < 0).sum())

No of Bedrooms Negative values: 0
No of Bathrooms Negative values: 0
Flat Area (in Sqft) Negative values: 0
Lot Area (in Sqft) Negative values: 0
Area of the House from Basement (in Sqft) Negative values: 0
Basement Area (in Sqft) Negative values: 0
Living Area after Renovation (in Sqft) Negative values: 0
Lot Area after Renovation (in Sqft) Negative values: 0

In [44]:
print("Final dataset shape after outlier treatment:")
print(data.shape)

Final dataset shape after outlier treatment:
(21608, 22)

#### Outlier Treatment: Outliers were detected using the IQR method. Since extreme values in housing features may represent legitimate large or luxury properties, IQR outliers were not removed automatically. The bedroom distribution was examined individually, and a single observation containing 33 bedrooms was identified as an extreme anomaly compared with the remaining data, where the next-highest value was 11 bedrooms. Therefore, only the 33-bedroom observation was removed, while other plausible extreme observations were retained.

## Scaling Numerical Variables

In [45]:
data.columns

Index(['ID', 'Sale Price', 'No of Bedrooms', 'No of Bathrooms',
       'Flat Area (in Sqft)', 'Lot Area (in Sqft)', 'No of Floors',
       'Waterfront View', 'No of Times Visited', 'Condition of the House',
       'Overall Grade', 'Area of the House from Basement (in Sqft)',
       'Basement Area (in Sqft)', 'Age of House (in Years)', 'Renovated Year',
       'Zipcode', 'Latitude', 'Longitude',
       'Living Area after Renovation (in Sqft)',
       'Lot Area after Renovation (in Sqft)', 'Sale Year', 'Sale Month'],
      dtype='object')

In [46]:
x = data.drop(columns=['Sale Price'])
y = data['Sale Price']

In [48]:
x.head()

,ID,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Waterfront View,No of Times Visited,Condition of the House,Overall Grade,...,Basement Area (in Sqft),Age of House (in Years),Renovated Year,Zipcode,Latitude,Longitude,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft),Sale Year,Sale Month
0,7129300520,3,1.00,1180.0,5650.0,1.0,0,0,3,7,...,0,63,0,98178.0,47.5112,-122.257,1340.0,5650,2017,10
1,6414100192,3,2.25,2570.0,7242.0,2.0,0,0,3,7,...,400,67,1991,98125.0,47.7210,-122.319,1690.0,7639,2017,12
2,5631500400,2,1.00,770.0,10000.0,1.0,0,0,3,6,...,0,85,0,98028.0,47.7379,-122.233,2720.0,8062,2016,2
3,2487200875,4,3.00,1960.0,5000.0,1.0,0,0,5,7,...,910,53,0,98136.0,47.5208,-122.393,1360.0,5000,2017,12
4,1954400510,3,2.00,1680.0,8080.0,1.0,0,0,3,8,...,0,31,0,98074.0,47.6168,-122.045,1800.0,7503,2016,2

In [49]:
y.head()

0    221900.0
1    538000.0
2    180000.0
3    604000.0
4    510000.0
Name: Sale Price, dtype: float64

In [50]:
x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.20,
    random_state=42
)

In [52]:
print("X_train:", x_train.shape)
print("X_test :", x_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train: (17286, 21)
X_test : (4322, 21)
y_train: (17286,)
y_test : (4322,)

In [53]:
features_to_scale = [
    'No of Bedrooms',
    'No of Bathrooms',
    'Flat Area (in Sqft)',
    'Lot Area (in Sqft)',
    'No of Floors',
    'Area of the House from Basement (in Sqft)',
    'Basement Area (in Sqft)',
    'Age of House (in Years)',
    'Living Area after Renovation (in Sqft)',
    'Lot Area after Renovation (in Sqft)'
]

In [54]:
scaler = StandardScaler()

In [55]:
x_train[features_to_scale] = scaler.fit_transform(
    x_train[features_to_scale]
)

In [56]:
x_test[features_to_scale] = scaler.transform(
    x_test[features_to_scale]
)

In [58]:
x_train[features_to_scale].head()

,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft)
16969,1.794594,4.051721,3.288683,0.208444,0.934062,3.992333,-0.655623,-1.191148,2.694548,0.358096
6250,-1.500759,-0.791315,-0.496259,-0.327550,0.934062,-0.851751,0.566286,-1.225071,-0.472321,-0.403378
13664,-0.402308,0.500161,0.321812,-0.171467,0.934062,0.706570,-0.655623,-0.648384,0.753563,-0.164398
7243,0.696143,1.145899,0.790840,-0.188783,0.934062,1.226011,-0.655623,-1.055457,2.373483,-0.178056
17291,0.696143,0.500161,0.212736,-0.085032,-0.914281,-0.296070,0.996217,0.131839,0.053058,-0.066430

In [59]:
x_train[features_to_scale].mean()

No of Bedrooms                              -2.980120e-17
No of Bathrooms                              2.688273e-16
Flat Area (in Sqft)                         -1.808624e-17
Lot Area (in Sqft)                           1.644204e-18
No of Floors                                 6.371290e-17
Area of the House from Basement (in Sqft)   -9.310305e-17
Basement Area (in Sqft)                      2.630726e-17
Age of House (in Years)                     -8.796491e-17
Living Area after Renovation (in Sqft)       6.042450e-17
Lot Area after Renovation (in Sqft)         -5.138137e-19
dtype: float64

In [60]:
x_train[features_to_scale].std()

No of Bedrooms                               1.000029
No of Bathrooms                              1.000029
Flat Area (in Sqft)                          1.000029
Lot Area (in Sqft)                           1.000029
No of Floors                                 1.000029
Area of the House from Basement (in Sqft)    1.000029
Basement Area (in Sqft)                      1.000029
Age of House (in Years)                      1.000029
Living Area after Renovation (in Sqft)       1.000029
Lot Area after Renovation (in Sqft)          1.000029
dtype: float64